
services:
  rag-backend-image:
    build:
      context: ./ 
      dockerfile: Dockerfile 
    env_file:
      - .env
    ports:
      - 8009:8009

  rag-frontend-image:
    build:
      context: ./streamlit_frontend 
      dockerfile: Dockerfile  
    env_file:
      - .env
    ports:
      - 8008:8008
    depends_on:
      - rag-backend-image
